apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cicd
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cicd
  template:
    metadata:
      labels:
        app: app-cicd
    spec:
      containers:
        - name: app
          image: docker.io/elyesad/app-cicd:v2
          ports:
            - containerPort: 8888
