apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cicd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/ElyesMR/infra-cicd
    targetRevision: HEAD
    path: apps/app-cicd
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
